# Site settings
title: Huw Diprose | Home
email: email@huwdiprose.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.huwdiprose.co.uk" # the base hostname & protocol for your site
twitter_username: huwdiprose
github_username:  huwd

# Build settings
markdown: kramdown

#Customisation
name: Huw Diprose