# Site settings
title: Huw Diprose | Home
email: mail@huwdiprose.co.uk
description: >
  Home page of Huw Diprose, UK based web engineer and data nerd
baseurl: ""
url: "https://huwdiprose.co.uk"
twitter_username: huwdiprose
github_username: huwd

# Build settings
markdown: kramdown

# Customisation
name: Huw Diprose
signature: Huw

# Folders
collections:
  weeknotes:
    output: true
    permalink: /weeknotes/:path/

permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
