# Jekyll SEO Site settings
title: Homepage - Huw Diprose
tagline: Huw's Homepage - My home on the web
description: >
  Home page of Huw Diprose, UK based web engineer and data nerd
email: mail@huwdiprose.co.uk
url: "https://huwdiprose.co.uk"
author:
  name: Huw Diprose
  url: https://huwdiprose.co.uk
social:
  name: Huw Diprose
  links:
    - https://bsky.app/profile/huwdiprose.bsky.social
    - https://x.com/huwdiprose
    - https://github.com/huwd
    - https://keybase.io/huwdiprose
seo:
  name: "Huw Diprose"
  twitter:
    username: "huwdiprose"
  github:
    username: "huwd"
locale: en_GB

baseurl: ""
# Build settings
markdown: kramdown

# Customisation
name: Huw Diprose
signature: Huw

# Folders
collections:
  weeknotes:
    output: true
    permalink: /weeknotes/:path/
  books:
    output: false   # you probably don’t want individual book pages


permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
