# Site settings
title: Huw Diprose | Home
email: mail@huwdiprose.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is the Home Page of Huw Diprose. UK based coder, web designer and
  data nerd.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huwdiprose.co.uk" # the base hostname & protocol for your site
twitter_username: huwdiprose
github_username:  huwd

# Build settings
markdown: kramdown

#Customisation
name: Huw Diprose