# Jekyll SEO Site settings
title: Homepage - Huw Diprose
tagline: Huw's Homepage - My home on the web
description: >
  Home page of Huw Diprose, UK based web engineer and data nerd
email: mail@huwdiprose.co.uk
url: "https://huwdiprose.co.uk"
author:
  name: Huw Diprose
  url: https://huwdiprose.co.uk
social:
  name: Huw Diprose
  links:
    - https://bsky.app/profile/huwdiprose.bsky.social
    - https://x.com/huwdiprose
    - https://github.com/huwd
    - https://keybase.io/huwdiprose
seo:
  name: "Huw Diprose"
  twitter:
    username: "huwdiprose"
  github:
    username: "huwd"
locale: en_GB

baseurl: ""
# Build settings
markdown: kramdown

# Publish dotfile directories (Jekyll excludes them by default)
include:
  - .well-known

# Customisation
name: Huw Diprose
signature: Huw

# Folders
collections:
  reviews:
    output: true
    permalink: /review/book/:year/:month/:day/:title/
  blogs:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  weeknotes:
    output: true
    permalink: /weeknotes/:path/
  books:
    output: true
    permalink: /review/book/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: books
    values:
      layout: book

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
