# Site settings
title: Huw Diprose | Home
email: mail@huwdiprose.co.uk
description: >
  This is the Home Page of Huw Diprose. UK based coder, web designer and
  data nerd.
baseurl: ""
url: "https://huwdiprose.co.uk"
twitter_username: huwdiprose
github_username: huwd

# Build settings
theme: frogmore
markdown: kramdown

# Customisation
name: Huw Diprose
signature: Huw
