publish_mode: editorial_workflow
site_url: https://huwdiprose.co.uk

backend:
  name: github
  repo: huwd/huwd.github.io
  branch: main
  base_url: https://auth-proxy.huwdiprose.co.uk
  # site_domain: localhost:4000

media_folder: /public
public_folder: /public

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "_posts/"
    preview_path: "/review/book/{{year}}/{{month}}/{{day}}/{{title}}"
    description: "Review of a books I have read"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Categories', name: 'categories', widget: 'list', default: ["review, book"] }
      - { label: 'Version', name: 'version', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About me"
        name: "about"
        file: "about.md"
        fields:
          - { label: 'Layout', name: 'layout' }
          - { label: 'Display Title', name: 'display_title', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "books"
    label: "Books"
    folder: "_books"
    create: true
    slug: "{{date_started}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Series", name: "series", widget: "string", required: false }
      - { label: "Series Entry", name: "series_entry", widget: "string", required: false }
      - { label: "Authors", name: "authors", widget: "list", summary: "{{fields.item}}" }
      - { label: "Work IRI", name: "work_iri", widget: "string", default : "https://www.wikidata.org/wiki/Q" }
      - { label: "Edition IRI", name: "edition_iri", widget: "string",  default : "https://www.wikidata.org/wiki/Q" }
      - { label: "Date Started", name: "date_started", widget: "datetime", summary: "{{fields.date_started}}" }
      - { label: "Date Finished", name: "date_finished", widget: "datetime", required: false }
      - { label: "Rating", name: "rating", widget: "number", required: false }