publish_mode: editorial_workflow
site_url: https://huwdiprose.co.uk

backend:
  name: github
  repo: huwd/huwd.github.io
  branch: main

media_folder: /public
public_folder: /public

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "_posts/"
    preview_path: "/review/book/{{year}}/{{month}}/{{day}}/{{title}}"
    description: "Review of a books I have read"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Categories', name: 'categories', widget: 'list', default: ["review, book"] }
      - { label: 'Version', name: 'version', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About me"
        name: "about"
        file: "about.md"
        fields:
          - { label: 'Layout', name: 'layout' }
          - { label: 'Display Title', name: 'display_title', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Data"
    name: "data"
    files:
      - label: "Reading Log"
        name: "books"
        file: "_data/decap_books.json"
        format: "json"
        fields:
          - label: "Reading Entry"
            name: "entry"
            widget: "list"
            fields:
              - {label: "Title", name: "title", :widget: string}

