publish_mode: editorial_workflow
site_url: https://huwdiprose.co.uk

backend:
  name: github
  repo: huwd/huwd.github.io
  branch: main
  base_url: https://auth-proxy.huwdiprose.co.uk
  # site_domain: localhost:4000

media_folder: /public
public_folder: /public

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "_posts/"
    preview_path: "/review/book/{{year}}/{{month}}/{{day}}/{{title}}"
    description: "Review of a books I have read"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Categories', name: 'categories', widget: 'list', default: ["review, book"] }
      - { label: 'Version', name: 'version', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About me"
        name: "about"
        file: "about.md"
        fields:
          - { label: 'Layout', name: 'layout' }
          - { label: 'Display Title', name: 'display_title', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Data"
    name: "data"
    files:
      - label: "Reading Log"
        name: "books"
        file: "_data/books.json"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Reading Entry"
            name: "entries"
            widget: "list"
            add_to_top: true
            fields:
              - { required: true, label: "Title", name: "title", widget: string }
              - { required: false, label: "Subtitle", name: "subtitle", widget: string }
              - { required: false, label: "Series", name: "series", widget: string }
              - { required: false, label: "Series Entry", name: "series_entry", widget: string }
              - { required: true, label: "Authors", name: "authors", widget: list }
              - { required: false, label: "Work IRI", name: "work_iri", widget: string }
              - { required: false, label: "Edition IRI", name: "edition_iri", widget: string }
              - { required: false, label: "Date Started", name: "date_started", widget: datetime }
              - { required: false, label: "Date Finished", name: "date_finished", widget: datetime }
              - { required: false, label: "Rating", name: "rating", widget: number, value_type: "int" }
              - { required: false, label: "Review URL", name: "review_url", widget: string }
